modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/JumpRightIn/issues"
license="MIT"

[[mods]]
modId="jumprightin"
version="${file.jarVersion}"
displayName="Jump Right In"
displayURL="https://www.curseforge.com/minecraft/mc-mods/jump-right-in"
authors="Mrbysco, Nekomaster1000"
description='''
Skip the main menu and get sent straight into a world!
'''
[[dependencies.jumprightin]]
modId="minecraft"
type="required"
versionRange="[26.1.1,)"
ordering="NONE"
side="BOTH"
[[dependencies.jumprightin]]
modId="neoforge"
type="required"
versionRange="[26.1.1.0-beta,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config="jumprightin.mixins.json"